name: build docs
on:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: install gustaf
        run:  |
          pip install -e .[all]

      - name: Install dependencies
        run:  pip install -r ./docs/requirements.txt

      - name: Sphinx config and extra docs
        run: |
          python3 docs/source/extra_docs.py
          python3 docs/source/handle_markdown.py

      - name: Sphinx build
        run: |
          sphinx-build -W -b html docs/source docs/build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          #publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          force_orphan: true
